name: firebase-deploy

on:
  push:
    branches:
      - master

permissions:
  id-token: write

jobs:
  deploy:
    environment: Production Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install yarn, firebase-tools
        run: npm install -g yarn firebase-tools
      - run: yarn install
      - run: yarn test
      - run: yarn build
        env:
          VITE_API_KEY: ${{ secrets.API_KEY }}
          VITE_APP_ID: ${{ secrets.APP_ID }}
          VITE_AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
          VITE_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          VITE_MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
          VITE_MEASUREMENT_ID: ${{ secrets.MEASUREMENT_ID }}
          VITE_PROJECT_ID: ${{ secrets.PROJECT_ID }}
          VITE_STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
      - id: 'auth'
        name: 'Authenticate to GCP'
        uses: 'google-github-actions/auth@v1'
        with:
            workload_identity_provider: 'https://iam.googleapis.com/projects/254727144997/locations/global/workloadIdentityPools/github-actions/providers/github'
            service_account: 'production-deploy@leaction.iam.gserviceaccount.com'
      - name: Firebase Production Deploy
        run: firebase deploy
